theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  search:
    active: false
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo-white.svg"
  menu:
    dropdown:
      linkToLevel1: true
  breadcrumb:
    position: after-hero