theme: osuny
pagination: 
  pagerSize: 18
enableRobotsTXT: true
removePathAccents: true
params:
  debug:
    productionUrl: "https://irisinstruments.netlify.app"
  summary:
    position: hero
  breadcrumb:
    position: hero-end
    footer:
  logo:
    header: "/assets/images/logo-white.svg"
    footer: "/assets/images/logo-white.svg"   
  menu:
    dropdown:
      linkToLevel1: false
  image_sizes:
    custom_cta:
      mobile:   70
      tablet:   70
      desktop:  70
    design_system:
      lightbox:
        disabled: true
    sections:
      home:
        hero:
          desktop:  1920
  i18n:
    positions:
      - primary
