theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  breadcrumb:
    position: hero-end
    footer:
  logo:
    header: "/assets/images/logo-white.svg"
    footer: "/assets/images/logo-white.svg"   
  menu:
    dropdown:
      linkToLevel1: false
  image_sizes:
    design_system:
      lightbox:
        disabled: true
    sections:
      home:
        hero:
          desktop:  1920